services:
  backend:
    build:
      context: ./salon-backend
      dockerfile: Dockerfile.backend
    container_name: salon-backend
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./salon-frontend
      dockerfile: Dockerfile.frontend
    container_name: salon-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
